package com.fireinyu.themyth.chatmodes;

import com.fireinyu.themyth.exceptions.InvalidCommandException;
import com.fireinyu.themyth.requests.AtRequest;
import com.fireinyu.themyth.requests.DeadlineRequest;
import com.fireinyu.themyth.requests.DeleteRequest;
import com.fireinyu.themyth.requests.DueRequest;
import com.fireinyu.themyth.requests.EventRequest;
import com.fireinyu.themyth.requests.ExitRequest;
import com.fireinyu.themyth.requests.ListRequest;
import com.fireinyu.themyth.requests.MarkRequest;
import com.fireinyu.themyth.requests.Request;
import com.fireinyu.themyth.requests.TodoRequest;
import com.fireinyu.themyth.requests.UnmarkRequest;
import com.fireinyu.themyth.requests.events.CloseRequest;
import com.fireinyu.themyth.requests.events.InitRequest;
import com.fireinyu.themyth.responses.Response;
import com.fireinyu.themyth.responses.ExitResponse;

/**
 * Represents an abstract chat mode that defines how to respond to various user requests.
 * Subclasses will implement the specific logic for handling different commands.
 */
public abstract class ChatMode {
    /**
     * Dispatches the given request to the appropriate handler method based on its type.
     * @param request The user request to respond to.
     * @return The response generated by the handler.
     */
    public Response respondTo(Request request) {
        return switch (request) {
            case InitRequest r -> respondToInit(r);
            case CloseRequest r -> respondToClose(r);
            case ExitRequest r -> respondToExit(r);
            case ListRequest r -> respondToList(r);
            case AtRequest r -> respondToAt(r);
            case DueRequest r -> respondToDue(r);
            case MarkRequest r -> respondToMark(r);
            case UnmarkRequest r -> respondToUnmark(r);
            case TodoRequest r -> respondToTodo(r);
            case DeadlineRequest r -> respondToDeadline(r);
            case EventRequest r -> respondToEvent(r);
            case DeleteRequest r -> respondToDelete(r);
            default -> respondToRemaining(request);
        };
    }

    /**
     * Handles any request that is not explicitly handled by other methods in this chat mode.
     * Throws an {@link InvalidCommandException} by default.
     *
     * @param request The request to handle.
     * @return A {@link Response} object.
     */
    protected Response respondToRemaining(Request request) {
        throw new InvalidCommandException(request);
    }

    /**
     * Handles the initialization request.
     *
     * @param request The initialization request.
     * @return A generic response indicating no handler is present.
     */
    protected Response respondToInit(InitRequest request) {
        return new Response("no init handler");
    }

    /**
     * Handles the close request.
     *
     * @param request The close request.
     * @return A generic response indicating no handler is present.
     */
    protected Response respondToClose(CloseRequest request) {
        return new Response("no close handler");
    }

    /**
     * Handles a {@link TodoRequest}.
     *
     * @param request The request to handle.
     * @return A {@link Response} object.
     */
    protected Response respondToTodo(TodoRequest request) {
        return respondToRemaining(request);
    }

    /**
     * Handles a {@link DeadlineRequest}.
     *
     * @param request The request to handle.
     * @return A {@link Response} object.
     */
    protected Response respondToDeadline(DeadlineRequest request) {
        return respondToRemaining(request);
    }

    /**
     * Handles an {@link EventRequest}.
     *
     * @param request The request to handle.
     * @return A {@link Response} object.
     */
    protected Response respondToEvent(EventRequest request) {
        return respondToRemaining(request);
    }

    /**
     * Handles an {@link UnmarkRequest}.
     *
     * @param request The request to handle.
     * @return A {@link Response} object.
     */
    protected Response respondToUnmark(UnmarkRequest request) {
        return respondToRemaining(request);
    }

    /**
     * Handles a {@link MarkRequest}.
     *
     * @param request The request to handle.
     * @return A {@link Response} object.
     */
    protected Response respondToMark(MarkRequest request) {
        return respondToRemaining(request);
    }

    /**
     * Handles a {@link ListRequest}.
     *
     * @param request The request to handle.
     * @return A {@link Response} object.
     */
    protected Response respondToList(ListRequest request) {
        return respondToRemaining(request);
    }

    /**
     * Handles an {@link AtRequest}.
     *
     * @param request The request to handle.
     * @return A {@link Response} object.
     */
    protected Response respondToAt(AtRequest request) {
        return respondToRemaining(request);
    }

    /**
     * Handles a {@link DueRequest}.
     *
     * @param request The request to handle.
     * @return A {@link Response} object.
     */
    protected Response respondToDue(DueRequest request) {
        return respondToRemaining(request);
    }

    /**
     * Handles a {@link DeleteRequest}.
     *
     * @param request The request to handle.
     * @return A {@link Response} object.
     */
    protected Response respondToDelete(DeleteRequest request) {
        return respondToRemaining(request);
    }

    /**
     * Handles an {@link ExitRequest}.
     *
     * @param request The request to handle.
     * @return An {@link ExitResponse} with a goodbye message.
     */
    protected Response respondToExit(ExitRequest request) {
        return new ExitResponse("Bye. Hope to see you again soon!");
    }
}
